# Generated by Django 5.1.6 on 2025-02-18 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Solicitante', models.CharField(default='-', max_length=200)),
                ('fechaInicioTrabajo', models.DateTimeField()),
                ('fechaFinTrabajo', models.DateTimeField()),
                ('ocupaVia', models.BooleanField(default=False)),
                ('necesitaCorteEnergia', models.BooleanField(default=False)),
                ('kmInicio', models.CharField(default='-', max_length=10)),
                ('PaloInicio', models.CharField(default='-', max_length=10)),
                ('kmFin', models.CharField(default='-', max_length=10)),
                ('paloFin', models.CharField(default='-', max_length=10)),
                ('via', models.CharField(default='No ocupa', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='-')),
                ('supervisorTransporte', models.BooleanField(default=False)),
                ('piloto', models.BooleanField(default=False)),
                ('personalPolicial', models.BooleanField(default=False)),
                ('otro', models.BooleanField(default=False)),
                ('detalleOtro', models.TextField(blank=True)),
                ('responsable', models.ManyToManyField(blank=True, to='Agenda.agenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estacionFin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circular_fin_set', to='cargaCircularTrabajo.estacion')),
                ('estacionInicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circular_inicio_set', to='cargaCircularTrabajo.estacion')),
            ],
        ),
    ]
