# Generated by Django 5.1.6 on 2025-02-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('apellidoYNombre', models.CharField(max_length=100)),
                ('subGerencia', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('interno', models.CharField(max_length=20)),
            ],
        ),
    ]
