# Generated by Django 5.1.6 on 2025-02-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('apellidoYNombre', models.CharField(max_length=100)),
                ('subGerencia', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('interno', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='circular',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
